import Head from 'next/head'
import React, { useCallback, useRef, useState } from 'react';
import DropdownPopUp from '../components/DropdownPopUp';
import { useClickOutside } from '../hooks/useClickOutside';
import s from '../styles/dropdown.module.scss'

export default function Dropdown() {    
    const [isOpen, setIsOpen] = useState<boolean>(false);
    const handleChange = () => { setIsOpen((state) => !state) }
    
    return (
        <div className="">
            <Head>
                <title>Dropdown</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <DropdownPopUp/>
        </div>
    )
}