import Head from 'next/head'
import React, { useCallback, useState } from 'react';
import s from '../styles/dropdown.module.scss'

export default function Dropdown() {
    const [isOpen, setIsOpen] = useState(false);
    const handleChange = () => { setIsOpen(!isOpen) }

    return (
        <div className="">
            <Head>
                <title>Dropdown</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className={s.wrapper}>
                <button onClick={handleChange} className={s.btn}>V</button>

                <div className={`${s.dropdown} ${isOpen ? s.show : s.hide}`}>
                    <p>content</p>
                </div>
            </section>
        </div>
    )
}